### ISSUE TITLE
How to convert python

### ISSUE THREAD

**Issue by kpgardner** [kpgardner/rgb-game#2]
I don't really understand how to convert my python code into html.

**Comment by chrisortman** [comment]
@kpgardner Thanks for the question! If you have any specific instances where you have python code but you're not sure how to get it onto the page I can look at your workspace, or you can link to it on github.

As a general answer to your question...

The way I like to think about it is to write the HTML that I want for just one page. Then look at it and ask, "What python do I need to write to produce this string" 

So the first step is to get 1 page to work, even though that means some of it you will redo or delete. (And since you know you will probably have to do those things, invest the bare minimum time into building out the HTML you need, hard code things that you know should be dynamic, copy and paste things when needed)

So once I've got the html that I want in some templates/folder/file.html I pick out the parts that need to be dynamic. So say you had something like

``` html
You are in room: <b>Armory</b>
```

And I say I want to make _Armory_ dynamic I add a variable to the page

``` html
You are in room: <b>{{ room }}</b>
```

Like this, then go to my views.py and change my function to pass it as a variable

``` python
context = { 'room' : 'Armory' }
```

And now that part of your page is dynamic. Later you can further change the python to look up Armory from a database or something, but it doesn't matter how you get it to the .html stuff.

One more example, say you have a list of choices

``` html
<ol>
<li>Go left</li>
<li>Go Right</li>
<li>Go Forward</li>
</ol>
```

And so now, you want that to come from python because that's where the game code is. So we do the same thing (you could do choice1, choice2, choice3 ...but a list will be easier)

``` html
<ol>
{% for c in choices %}
  <li>{{ c }}</li>
{% endfor %}
</ol>
```

And then in python

``` python
context = { 'room' : 'Armory', 'choices' : ['Go Left', 'Go Right', 'Go Forward'] }
```

You can see other things you can do with `{%` here 

https://docs.djangoproject.com/en/1.9/topics/templates/#the-django-template-language

And remember, once you know the HTML you are trying to produce it's much easier to figure out what python you need.
